# stages: 파이프라인의 실행 단계를 정의합니다.
stages:
  - build
  - deploy

# build: Docker 이미지를 빌드하고 ECR에 푸시하는 단계입니다.
build:
  stage: build
  # Docker CLI와 Docker-in-Docker(dind)를 사용하기 위한 이미지입니다.
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: ''
  # 스크립트 실행 전에 Docker에 로그인합니다.
  before_script:
    - apk add --no-cache curl
    - apk add --no-cache python3 py3-pip
    - pip install awscli
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set default.region "$AWS_DEFAULT_REGION"
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL

  script:
    - docker build -t alcha-frontend:latest .
    - docker tag alcha-frontend:latest $ECR_REGISTRY_URL:$CI_PIPELINE_ID
    - docker push $ECR_REGISTRY_URL:$CI_PIPELINE_ID

  # main 브랜치에 푸시될 때만 이 단계가 실행됩니다.
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

  tags:
    - alcha-frontend

deploy:
  stage: deploy
  # sed 명령을 포함하는 경량 이미지를 사용합니다.
  image: alpine/git:latest

  before_script:
    # --- SSH 클라이언트 및 에이전트 설정 ---
    - apk add openssh-client
    
    # 1. SSH Agent 시작
    - eval $(ssh-agent -s)
    
    # 2. File 변수 경로를 사용하여 Agent에 키 로드 (권한은 GitLab Runner가 이미 관리)
    # $GITOPS_REPO_SSH_KEY 변수에는 SSH 개인 키의 임시 파일 경로가 담겨 있습니다.
    - ssh-add "$GITOPS_REPO_SSH_KEY" > /dev/null
    
    # 3. GitLab 서버를 신뢰할 수 있는 호스트로 등록
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 4.230.1.132 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - export NEW_TAG=$CI_PIPELINE_ID
    # ECR_REGISTRY_URL 변수를 사용하여 최종 이미지 URL을 생성합니다.
    - export FULL_IMAGE_URL="${ECR_REGISTRY_URL}:${NEW_TAG}" 
    
    # 1. GitOps 저장소 클론
    - git clone git@4.230.1.132:carpoor/alcha-gitops.git
    - cd alcha-gitops
    
    # 2. git 사용자 정보 설정
    - git config user.name "GitLab CI Runner"
    - git config user.email "ci-runner@gitlab.com"

    # 3. deployment.yaml 파일 수정 (sed 사용)
    # 기존 플레이스홀더를 FULL_IMAGE_URL 값으로 치환합니다.
    # 주의: sed 패턴에 슬래시(/)가 포함될 경우 구분자로 다른 문자(예: |)를 사용합니다.
    - sed -i "s|__ECR_REGISTRY_URL__:latest|${ECR_REGISTRY_URL}:${NEW_TAG}|" deployment.yaml
    
    # 4. Git Write Back (커밋 및 푸시)
    # 수정된 deployment.yaml 파일만 추적하고 커밋합니다.
    - git add deployment.yaml
    
    # 5. 변경 사항이 있을 경우에만 커밋하도록 처리
    - |
      if ! git diff-index --quiet HEAD; then
        echo "Updating image tag and pushing to GitOps repo."
        git commit -m "ci: Update React app image tag to ${NEW_TAG}"
        git push origin HEAD:main
      else
        echo "No changes detected in deployment.yaml. Skipping commit."
      fi
  tags:
    - alcha-frontend